# Site settings
title: Code MESsy
header-img: img/home-bg.png
email: mollie.stein@gmail.com
copyright_name: mess3109
description: > # this means to ignore newlines until "baseurl:"
  Always Be Learning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mess3109
learn_profile: mess3109
email_username: mollie.stein@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
